#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

DICT="-decomposeParDict system/decomposeParDict.2"

START=$(date +%s%3N)

rm -rf proc*

rm -rf 0
cp -r 0.orig 0

echo Running blockMesh...

blockMesh > /dev/null 2>&1

echo done

surfaceFeatureExtract > /dev/null 2>&1

decomposePar > /dev/null 2>&1 

echo Running snappyHexMesh...

mpirun -np 6 snappyHexMesh -overwrite -parallel 

echo done

echo cleaning up...
reconstructParMesh -constant > /dev/null 2>&1

extrudeMesh > /dev/null 2>&1

rm -rf proc*

changeDictionary > /dev/null 2>&1

checkMesh -allGeometry -allTopology > meshCheck.log


TIME=$((( $(date +%s%3N) - START ) / 1000))
echo "done in $TIME sec"

