#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

python updateStatus.py 1

python mesher.py

python updateStatus.py 2

./Simplerun

# python updateStatus.py 3

# ./Pimplerun

foamToVTK -latestTime
#add the data extraction...

#------------------------------------------------------------------------------
