#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

python updateStatus.py 1

echo "meshing..."

python mesher.py

python updateStatus.py 2

echo "solving..."

./Simplerun


foamToVTK -latestTime
#add the data extraction...

#------------------------------------------------------------------------------
